---
baseURL: http://wellbeing-aachen.de/
languageCode: de-DE
title: Wellbeing-Aachen | Paula Aguirre
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: de
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: 'images/corporate/logo.png'
  description: Wellbeing Aachen - Wohlfühlen hat eine neue Adresse.
  facebook: ''
  twitter: 
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-darkgreen
  featured_image: "/images/default/wellbeing-aachen.jpg"
  recent_posts_number: 2
menu:
  main:
  - name: Paula Aguirre
    weight: 3
  - name: Neu: Focusing
    weight: 2
  - name: Behandlungen
    weight: 1
